version: '2'
services:
  novnc:
    #image: dorowu/ubuntu-desktop-lxde-vnc:focal
    image: dorowu/ubuntu-desktop-lxde-vnc
    hostname: noVNClinux
    cap_add:
      #Google Chrome require this: https://github.com/jessfraz/dockerfiles/issues/65
      - SYS_ADMIN
    ports:
      - '80:80'
    environment:
      - USER=ubuntu